Dynamic table, dynamic breadcrumb, employee layout, linting (2)
tatsmaki/cv-generator pull request #22
Opened 2022-08-01 11:28 UTC by twentysixhugs

2022-08-01 11:58 UTC, murashkoIl submitted a review, later dismissed

2022-08-02 09:11 UTC, tatsmaki requested changes

2022-08-02 09:11 UTC, tatsmaki commented on src/components/Router/Router.tsx
>  import { ProjectsPage } from "../../pages/ProjectsPage/ProjectsPage";
пора бы добавить алиасы

2022-08-02 09:11 UTC, tatsmaki commented on src/components/Table/Table.tsx
> +      {[...items].sort(byColumn<Item>(sortBy, sortAsc)).map((item) => (
зачем копия?

2022-08-02 09:11 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeInfoPage/EmployeeInfoPage.tsx
> +import { EmployeeBreadcrumbSwitcher } from "../../../../components/Breadcrumb/helpers/EmployeeBreadcrumbSwitcher";
алиасы

2022-08-02 09:30 UTC, twentysixhugs commented on src/components/Breadcrumb/Breadcrumb.tsx
> +          pathnames.current.findIndex((pathname) => pathname === params[param]),
нет, тут максимум н2 и отработает он быстро, так как количество элементов для итерации ничтожно мало, енто ж бредкрамб. forEach, а внутри него 2n: includes и findIndex, что равно n. Итого получается n2, хотя по большому счету внешний цикл итерируется по одному массиву, а внутренний по другому.

2022-08-02 09:36 UTC, twentysixhugs commented on src/components/App/App.tsx
> +export function App() {
це еслинт, це не мы. Не заметили и закоммитили аирбнб кодстайл. Мы его уже отключили

2022-08-02 09:38 UTC, twentysixhugs commented on src/components/Table/Table.tsx
> +      {[...items].sort(byColumn<Item>(sortBy, sortAsc)).map((item) => (
так как Array.prototype.sort не только возвращает новый массив, но и модифицирует оригинальный. items - это пропсы, а их модифицировать нельзя.

2022-08-02 09:38 UTC, tatsmaki commented on src/components/App/App.tsx
> +export function App() {
так а в чем разница для компонента?)

2022-08-02 09:40 UTC, murashkoIl commented on src/components/App/App.tsx
> +export function App() {
дык ничего не поменяется)

2022-08-02 10:17 UTC, tatsmaki commented on src/components/App/App.tsx
> +export function App() {
а если типизировать? что делает FC?

2022-08-02 10:18 UTC, tatsmaki commented on src/components/App/App.tsx
> +export function App() {
@murashkoIl тыкни Иаана, я ему по бредкрамбам скинул

2022-08-02 11:16 UTC, twentysixhugs commented on src/components/App/App.tsx
> +export function App() {
@tatsmaki вроде бы у фц что-то с чилдрен

2022-08-02 14:59 UTC, tatsmaki requested changes

2022-08-02 14:59 UTC, tatsmaki commented on craco.config.js
> +      "@": path.resolve(__dirname, "src"),
эм
@pages
@component
@constants
etc

2022-08-02 14:59 UTC, tatsmaki commented on src/components/PageTopTypography/PageTopTypography.tsx
> +      <Typography variant="h6">{title}</Typography>
h6 не существует, как тега так и варианта типографии в mui

2022-08-02 14:59 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeePage/EmployeePage.tsx
> +        <Typography variant="h6">Employees</Typography>
компонент для заголовка страницы
![image](https://user-images.githubusercontent.com/61022192/182405329-e30be15a-4e99-4b84-9d7b-2ba1aae070a0.png)

2022-08-02 14:59 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeInfo/EmployeeInfo.tsx
> +            <Controller
откатите форму, и откройте ревью от новой ветки
в чем разница между Controller и register?

2022-08-02 14:59 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeInfo/EmployeeInfo.tsx
> +            <Typography>Specialization</Typography>
TextField.label

2022-08-02 14:59 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeInfo/EmployeeInfo.tsx
> +          <div className="textfield-wrapper">
delete

2022-08-02 14:59 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeInfo/EmployeeInfo.tsx
> +        <div className="buttons">
DialogActions или создайте свой компонент FormActions

2022-08-02 14:59 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeInfo/EmployeeInfo.tsx
> +        <InfoFormWrapper>
DialogContent или свой FormContent

2022-08-02 14:59 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeInfo/EmployeeInfo.tsx
> +                  error={!!errors.specialization?.message}
поле ошибки по умолчанию undefined или null
!!errors.specialization

2022-08-02 14:59 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeInfo/EmployeeInfo.tsx
> +              defaultValue={employee.specialization}
defaultValue лучше прописывать в хуке формы

2022-08-02 14:59 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeInfo/EmployeeInfo.tsx
> +                  helperText={errors.department?.message || " "}
required проп

2022-08-02 14:59 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeInfo/EmployeeInfo.tsx
> +                  error={!!errors.email?.message}
required проп

2022-08-03 08:07 UTC, tatsmaki commented on package.json
> +    "react-app-alias": "^2.2.1",
?

2022-08-03 08:08 UTC, tatsmaki commented on src/components/Breadcrumb/Breadcrumb.tsx
> +        console.log(routeTo);
лог

2022-08-03 08:12 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeePage/EmployeePage.tsx
> +  console.log("REDNER");
лог

2022-08-03 12:08 UTC, tatsmaki approved these changes

2022-08-03 12:09 UTC, merged