Styling enhance
tatsmaki/cv-generator pull request #26
Opened 2022-08-04 09:14 UTC by murashkoIl

2022-08-04 09:44 UTC, twentysixhugs approved these changes

2022-08-04 11:13 UTC, tatsmaki requested changes

2022-08-04 11:13 UTC, tatsmaki commented on src/components/FormActions/FormActions.tsx
> +  return <StyledFormActions>{children}</StyledFormActions>;
DialogActions

2022-08-04 11:13 UTC, tatsmaki commented on src/components/FormActions/FormActions.styles.ts
> +  gap: "1em",
flex gap не работает во всех браузерах
по дефолту в mui в DialogActions используется spacing: 2

2022-08-04 11:13 UTC, tatsmaki commented on src/components/FormActions/FormActions.styles.ts
> +export const StyledFormActions = styled("div")({
DialogActions

2022-08-04 11:13 UTC, tatsmaki commented on src/components/ProjectInfo/ProjectInfo.tsx
> +    <form onSubmit={handleSubmit(onSubmit)}>
DialogContent

2022-08-04 11:13 UTC, tatsmaki commented on src/components/ProjectInfo/ProjectInfo.tsx
> +      </StyledFormActions>
DialogActions

2022-08-04 11:13 UTC, tatsmaki commented on src/components/ProjectInfo/ProjectInfo.tsx
> +};
уменьшить файл до 60 строк

2022-08-04 11:13 UTC, tatsmaki commented on src/components/ProjectInfo/ProjectInfo.tsx
> +          <FormLabel required={true}>Description</FormLabel>
label проп у TextField

2022-08-04 11:13 UTC, tatsmaki commented on src/components/ProjectInfo/ProjectInfo.tsx
> +          <FormLabel required={true}>Domain</FormLabel>
label проп у TextField

2022-08-04 11:13 UTC, tatsmaki commented on src/components/ProjectInfo/ProjectInfo.tsx
> +          <FormLabel required={true}>End date</FormLabel>
label проп у TextField

2022-08-04 11:13 UTC, tatsmaki commented on src/components/ProjectInfo/ProjectInfo.tsx
> +          <FormLabel required={true}>Start date</FormLabel>
label проп у TextField

2022-08-04 11:13 UTC, tatsmaki commented on src/components/ProjectInfo/ProjectInfo.tsx
> +          <FormLabel required={true}>Name</FormLabel>
label проп у TextField

2022-08-04 11:13 UTC, tatsmaki commented on src/components/ProjectInfo/ProjectInfo.tsx
> +          <FormLabel required={true}>Internal name</FormLabel>
label проп у TextField

2022-08-04 11:13 UTC, tatsmaki commented on src/pages/CvsPage/CvsPage.tsx
> +  },
убрать мок данные из компонента

2022-08-04 11:13 UTC, tatsmaki commented on src/pages/CvsPage/components/CvInfo/CvInfo.tsx
> +};
те же замечания, что и к предыдущей форме

2022-08-04 11:13 UTC, tatsmaki commented on src/pages/EmployeesPage/EmployeesPage.tsx
>    {
убрать мок данные из компонента

2022-08-04 11:13 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeCv/components/CvItem/CvItem.tsx
> +    cvs.filter((cv: any) => cv.id !== id);
а куда сохраняется результат фильтра? убрать unused код

2022-08-04 11:13 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeCv/components/CvItem/CvItem.tsx
> +type CvItemProps = {
типы в отдельный файл компонента

2022-08-04 11:13 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeInfo/EmployeeInfo.tsx
> +};
аналогично

2022-08-04 11:13 UTC, tatsmaki commented on src/pages/ProjectsPage/ProjectsPage.tsx
> +  {
убрать мок данные из файла

2022-08-04 11:23 UTC, twentysixhugs commented on src/components/ProjectInfo/ProjectInfo.tsx
> +          <FormLabel required={true}>Description</FormLabel>
> label проп у TextField

тогда не будет соответствовать дизам

2022-08-04 13:19 UTC, twentysixhugs commented on src/components/ProjectInfo/ProjectInfo.tsx
> +    <form onSubmit={handleSubmit(onSubmit)}>
он скроллбар показывает

2022-08-04 13:20 UTC, twentysixhugs commented on src/components/ProjectInfo/ProjectInfo.tsx
> +};
компонент и типизация есть, вёрстка не повторяется, но в нем много пропов. строк 160, но выглядит все теперь красиво (позже закоммичу)

2022-08-04 15:22 UTC, tatsmaki commented on src/components/Fieldset/Fieldset.types.ts
> +type OwnControllerProps<T> = Partial<Pick<ControllerProps<T>, "render">>;
export type FieldsetProps<T> = TextFieldProps & {
    name: Path<T>
    control: Control<T>
}
не мутите такую ерунду с ts, хуй прочтешь

2022-08-08 07:24 UTC, tatsmaki requested changes

2022-08-08 07:24 UTC, tatsmaki commented on src/components/Fieldset/Fieldset.tsx
> +      <FormLabel required={!!required}>{label}</FormLabel>
давайте, застилизуйте ее уже в TextField

2022-08-08 08:07 UTC, tatsmaki approved these changes

2022-08-08 08:08 UTC, merged