Feature/setup redux
tatsmaki/cv-generator pull request #28
Opened 2022-08-08 11:14 UTC by twentysixhugs

2022-08-08 13:01 UTC, tatsmaki requested changes

2022-08-08 13:01 UTC, tatsmaki commented on src/pages/CvsPage/components/CvInfo/CvInfo.tsx
> +  const cv = cvsMock.find(({ id }) => id === cvId)!;
тут запрос на cv без вариантов, проектов в массиве с сивишками не будет
проекты доступны при запросе на конкретный cv

2022-08-08 16:41 UTC, twentysixhugs commented on src/features/cvs/cvsSlice.types.ts
> +    data: { [T in keyof ICV]: ICV[T] };
ну, ты вот хочешь обновить в сивишке какое-нибудь поле, и ты передаешь объект именно с этими полями. Например, для объекта, в котором есть, скажем, name, description, author, prop1, prop2, propEtc, ты передаешь data: {name: 'some new name', description: 'some new description'}, и обновляешь этим самым name и description.
Что-то подобное реализовано в firebase в updateDoc()

2022-08-08 16:44 UTC, twentysixhugs commented on src/interfaces/ICV.ts
> +  [key: string]: string;
Проблема в том, что в таблице есть Item, который описывает, как выглядят айтемы в таблице: {[key: string]: string | number}, т.е. то, что таблица вообще может рендерить. Если я уберу в интерфейсе ICV и других этот самый [key: string], то почему-то мне пишет, что index signature for type 'string' is missing in type ICV. Как это можно исправить?

2022-08-08 16:44 UTC, twentysixhugs commented on src/pages/CvsPage/components/CvInfo/CvInfo.tsx
> +  const cv = cvsMock.find(({ id }) => id === cvId)!;
да, естественно так и будем делать, пока просто так оставлено, пока нет бэка

2022-08-08 16:45 UTC, twentysixhugs commented on src/components/ProjectInfo/ProjectInfo.tsx
> +    state.projects.find(({ id }) => id === projectId),
сделаю, как только сделаем бек

2022-08-09 08:52 UTC, murashkoIl approved these changes

2022-08-10 08:26 UTC, tatsmaki approved these changes

2022-08-10 08:26 UTC, merged