Feature/auth
tatsmaki/cv-generator pull request #30
Opened 2022-08-08 11:19 UTC by murashkoIl

2022-08-08 11:21 UTC, twentysixhugs commented on src/components/Router/Router.tsx
> +        <Route index element={<RedirectPage to={ROUTE.SIGN_IN} />} />
Нужно определять состяние аутентификации и делать редирект в зависимости от него на эмплоии или авторизацию

2022-08-08 11:25 UTC, twentysixhugs requested changes
Редирект

2022-08-08 11:25 UTC, twentysixhugs commented on src/components/Router/Router.tsx
> +        <Route index element={<RedirectPage to={ROUTE.SIGN_IN} />} />
Можно сделать мок состояния аутентификации, пока она не написана.

2022-08-08 13:19 UTC, tatsmaki commented on src/pages/ResetPassword/ResetPassword.tsx
> +        <AuthImg src={logoBlack} alt="logo" />
@murashkoIl можешь скинуть дизы на форму?

2022-08-09 08:47 UTC, twentysixhugs approved these changes

2022-08-09 15:00 UTC, tatsmaki approved these changes

2022-08-09 15:01 UTC, merged